# -*- coding: utf-8 -*-
"""AGE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FENZHm3CXgjqza7Tb4cQDlENVXxpkq7f
"""

from google.colab import files
uplo = files.upload()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

import plotly.express as px

import pandas as pd
df= pd.read_csv("Provisional_COVID-19_Deaths_Counts_by_Age_in_Years - Copy (2).csv")
df

###which age group had more danger
top5_active = pd.DataFrame(df.groupby('Age Years')['COVID-19 Deaths'].sum().nlargest(5).sort_values(ascending = False))
fig2 = px.scatter(top5_active, x = top5_active.index, y = 'COVID-19 Deaths', size = 'COVID-19 Deaths', size_max = 120,
                color = top5_active.index, title = 'Top 5 AGES IN RISK')
fig2.show()

top5Confirmed = pd.DataFrame(df.groupby('Age Years')['COVID-19 Deaths'].sum().nlargest(5).sort_values(ascending = False))
fig = px.density_contour(top5Confirmed, x = top5Confirmed.index, y = 'COVID-19 Deaths', height = 500, width = 700, color = 'COVID-19 Deaths',
             title = 'Top 5  AGES IN RISK')
fig.show()

m=df.groupby('Age Years')['COVID-19 Deaths'].sum().sort_values(ascending=False)
m

m.plot.bar(figsize=(20,5))
plt.show()

m1=df.groupby('Sex')['COVID-19 Deaths'].sum().sort_values(ascending=False)
m1

m5.plot.pie()
plt.show()

m1.plot.pie()
plt.show()

m2=df[df['Sex']=='Male'].groupby('Age Years')['COVID-19 Deaths'].sum().sort_values(ascending=False)
m2

m2.plot.bar(figsize=(20,5))
plt.show()

m3=df[df['Sex']=='Female'].groupby('Age Years')['COVID-19 Deaths'].sum().sort_values(ascending=False)
m3

m3.plot.bar(figsize=(20,5))
plt.show()

m4=df.groupby('Age Years')['Total deaths'].sum().sort_values(ascending=False)
m4

import seaborn as sns
sns.distplot(df['COVID-19 Deaths'].dropna())

sns.distplot(df['Total deaths'].dropna())

up=df['COVID-19 Deaths'].mean()+3*df['COVID-19 Deaths'].std()
lb=df['COVID-19 Deaths'].mean()-3*df['COVID-19 Deaths'].std()
print(up),print(lb)

df.hist(column='COVID-19 Deaths')

df.boxplot(column=['COVID-19 Deaths'])

df['COVID-19 Deaths'].describe()

####removed upper boundry outlier and skeweed 
df.loc[df['COVID-19 Deaths']>=24988,'COVID-19 Deaths']=24988
df.hist(column='COVID-19 Deaths')

fig = px.line(data_frame = df, x = 'Age Years', y="COVID-19 Deaths")
fig.update_xaxes(rangeslider_visible=False)
fig.show()

sns.distplot(df['COVID-19 Deaths'].dropna())

df.boxplot(column=['COVID-19 Deaths'])

fig=px.line(data_frame=df,x="Age Years",y="COVID-19 Deaths")
fig.update_xaxes(rangeslider_visible=True)
fig.show()

df.boxplot(by="Age Years",column=['COVID-19 Deaths'])

fig = px.line(data_frame = df, x = 'Age Years', y="COVID-19 Deaths")
fig.update_xaxes(rangeslider_visible=False)
fig.show()