# -*- coding: utf-8 -*-
"""severity

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pbGSP4dJaqdrRTO3paQeyqZNRLb6ucsj
"""

import pandas as pd

from google.colab import files
uplo = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import scipy.stats as stats

df=pd.read_csv("covid_cleaned - Copy (2).csv")
df

df7= df.fillna(value='0')
df7

df1=df7[df7['died']==1]
df1

dfb=df1['sex'].value_counts()
dfb

dfb=df1['age'].value_counts()
dfb

df1['pneumonia'].value_counts()

df1['diabetes'].value_counts()

df1['copd'].value_counts()

df1['asthma'].value_counts()

df1['inmsupr'].value_counts()

df1['hypertension'].value_counts()

df1['other_disease'].value_counts()

df1['cardiovascular'].value_counts()

df1['obesity'].value_counts()

df1['renal_chronic'].value_counts()

data = { 
       1:[11752,4942,650,272,413, 5177,456,812,3450,805], 
       0:[1571, 8381,12673,13051,12910,8146,12867,12511,3450, 12518]
       }
dff=pd.DataFrame(data, index= ['pneumonia','diabetes','copd','asthma','inmsupr','hypertension','other_disease','cardiovascular','obesity','renal_chronic'])
dff

fig=px.line(data_frame=df,x="age",y="died")
fig.update_xaxes(rangeslider_visible=True)
fig.show()



dff.plot.pie(subplots=True, figsize=(51, 12),autopct="%.1f%%")

dff.plot(kind='bar', stacked='True')

df4=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)]
df4

dfs=df4['sex'].value_counts()
dfs

dfs.plot.pie()
plt.show()

#due to contact male and female got covid in the same percentage

dfa=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['diabetes']==1)]
dfa

dfo=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['obesity']==1)]
dfo

dfp=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['pneumonia']==1)]
dfp

dfa2=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['asthma']==1)]
dfa2

dfi=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['inmsupr']==1)]
dfi

dfh=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['hypertension']==1)]
dfh

dfc=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['copd']==1)]
dfc

dfca=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['cardiovascular']==1)]
dfca

dfr=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['renal_chronic']==1)]
dfr

dfp=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['pneumonia']==1)]
dfp

dfo=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['obesity']==1)]
dfo

dfa=df7[(df7['contact_other_covid']==1 )&(df7['covid_res']==1)&(df7['diabetes']==1)]
dfa

data1 = { 
       1:[9662,8363,734,2178,696,10867,1359,14140,832]
       }
dff1=pd.DataFrame(data1, index= ['pneumonia','diabetes','copd','asthma','inmsupr','hypertension','cardiovascular','obesity','renal_chronic'])
dff1

dff1.plot.pie(subplots=True, figsize=(51, 12),autopct="%.1f%%")

dff1.plot(kind='bar', stacked='True')

df21=df7[(df7['died']==1 )&(df7['covid_res']==1)&(df7['asthma']==1)]
df21

dfi1=df7[(df7['died']==1 )&(df7['covid_res']==1)&(df7['inmsupr']==1)]
dfi1

dfh1=df7[(df7['died']==1 )&(df7['covid_res']==1)&(df7['hypertension']==1)]
dfh1

dfc1=df7[(df7['died']==1 )&(df7['covid_res']==1)&(df7['copd']==1)]
dfc1

dfca1=df7[(df7['died']==1 )&(df7['covid_res']==1)&(df7['cardiovascular']==1)]
dfca1

dfr1=df7[(df7['died']==1 )&(df7['covid_res']==1)&(df7['renal_chronic']==1)]
dfr1

dfp1=df7[(df7['died']==1 )&(df7['covid_res']==1)&(df7['pneumonia']==1)]
dfp1

dfo1=df7[(df7['died']==1 )&(df7['covid_res']==1)&(df7['obesity']==1)]
dfo1

dfa1=df7[(df7['died']==1 )&(df7['covid_res']==1)&(df7['diabetes']==1)]
dfa1

data2 = { 
       1:[9663,4038,459,226,258,4265,585,2974,565]
       }
dff2=pd.DataFrame(data2, index= ['pneumonia','diabetes','copd','asthma','inmsupr','hypertension','cardiovascular','obesity','renal_chronic'])
dff2

dff2.plot.pie(subplots=True, figsize=(51, 12),autopct="%.1f%%")

dff2.plot(kind='bar', stacked='True')

m=df3.groupby('Row Labels')['Sum of died'].sum().sort_values(ascending=False)
m

m.plot.bar(figsize=(30,5))
plt.show()



top5Confirmed = pd.DataFrame(df3.groupby('Row Labels')['Sum of died'].sum().nlargest(5).sort_values(ascending = False))
fig = px.density_contour(top5Confirmed, x = top5Confirmed.index, y = 'Sum of died', height = 500, width = 700, color = 'Sum of died',
             title = 'Top 5 AGE GROUPS IN DANGER')
fig.show()

###which age group had more danger
top5_active = pd.DataFrame(df3.groupby('Row Labels')['Sum of died'].sum().nlargest(5).sort_values(ascending = False))
fig2 = px.scatter(top5_active, x = top5_active.index, y = 'Sum of died', size = 'Sum of died', size_max = 120,
                color = top5_active.index, title = 'Top 5 AGE GROUPS IN DANGER')
fig2.show()

ax = sns.violinplot(x='diseases', y="died", hue="died",

                    data=df1, palette="muted")
ax